[package]
name = "torrents_digger_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
lib_torrents_digger = { path = "../lib_torrents_digger" }
ratatui = "0.29.0"
